# Production Docker Compose Configuration
# Use this with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# This overrides the development configuration for production use

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    restart: always
    environment:
      NODE_ENV: production
      # Override with production MongoDB Atlas instead of local MongoDB
      MONGODB_URI: ${MONGODB_URI}
    # Remove mongodb dependency for production (use Atlas)
    depends_on: []
    
  # Don't start MongoDB in production (use MongoDB Atlas)
  mongodb:
    profiles:
      - local-only
